questions_list = [
         ("The process of pickling in Python includes ____________",
          "conversion of a Python object hierarchy into byte stream", "conversion of a data-table into a list",
          "conversion of a byte stream into Python object hierarchy", "conversion of a list into a datatable", "A"),
         ("________ matches the start of the string.________ matches the end of the string.", "^, $", "$, ^", "$, ?",
          "?, ^", "A"),
         ("Suppose B is a subclass of A, to invoke the __init__ method in A from B, what is the line of code you should write?",
         "A.__init__(self)", "super().__init__(self)", "A.__init__(B)", "Both A & B", "D"),
         ("Which of the following data types is immutable in Python?", "Tuple", "Set", "Dictionary", "List", "A"),
         ("What is the use of seek() method in files?", "sets the file’s previous position at the offset",
          "sets the file’s current position at the offset", "sets the file’s current position within the file",
          "None of the above", "B"),
         ("Which of the following is not a standard exception in Python?", "NameError", "IOError", "AssignmentError",
          "ValueError", "C"),
         ("What will be the output of the following Python code snippet? print('Ab!2'.swapcase())", "AB!@", " ab12",
          "aB!2", "aB1@", "C"),
         ("Which of the following functions will return the symmetric difference between two sets, x and y?", "x | y",
          "x ^ y", " x & y", "x – y", "B"),
         ("What is the order of namespaces in which Python looks for an identifier?",
          "Python first searches the built-in namespace, then the global namespace and finally the local namespace",
          "Python first searches the built-in namespace, then the local namespace and finally the global namespace",
          "Python first searches the local namespace, then the global namespace and finally the built-in namespace",
          "Python first searches the global namespace, then the local namespace and finally the built-in namespace",
          "C"),
         ("Who developed Python Programming Language?", "Wick van Rossum", "Guido van Rossum", "Rasmus Lerdorf",
          "Niene Stom", "B")
     ]